//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResxResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResxResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restaurante.Data.Resources.ResxResponses", typeof(ResxResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string contentTypeJson {
            get {
                return ResourceManager.GetString("contentTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales correctas..
        /// </summary>
        public static string log200Authentication {
            get {
                return ResourceManager.GetString("log200Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad solicitada se encontró correctamente..
        /// </summary>
        public static string log200Ok {
            get {
                return ResourceManager.GetString("log200Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad se registró correctamente..
        /// </summary>
        public static string log201Create {
            get {
                return ResourceManager.GetString("log201Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron resultados por error inesperado..
        /// </summary>
        public static string log204NoContent {
            get {
                return ResourceManager.GetString("log204NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise los datos enviados: .
        /// </summary>
        public static string log400BadRequest {
            get {
                return ResourceManager.GetString("log400BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron resultados..
        /// </summary>
        public static string log404NotFound {
            get {
                return ResourceManager.GetString("log404NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron productos por error inesperado..
        /// </summary>
        public static string log409Conflict {
            get {
                return ResourceManager.GetString("log409Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción por error inesperado..
        /// </summary>
        public static string log500NotControledException {
            get {
                return ResourceManager.GetString("log500NotControledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Success product retrieved in: {1} method..
        /// </summary>
        public static string logGetNoFilters {
            get {
                return ResourceManager.GetString("logGetNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Success product retrieved in: {1} method..
        /// </summary>
        public static string logGetWithFilters {
            get {
                return ResourceManager.GetString("logGetWithFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new violation exception has been thrown:.
        /// </summary>
        public static string logMiddlewareAccessViolation {
            get {
                return ResourceManager.GetString("logMiddlewareAccessViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong:.
        /// </summary>
        public static string logMiddlewareException {
            get {
                return ResourceManager.GetString("logMiddlewareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access violation error from the custom middleware.
        /// </summary>
        public static string middlewareCusomAccessViolation {
            get {
                return ResourceManager.GetString("middlewareCusomAccessViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! .
        /// </summary>
        public static string middlewareCusomException {
            get {
                return ResourceManager.GetString("middlewareCusomException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getByIdProduct.
        /// </summary>
        public static string productGetByIdMethod {
            get {
                return ResourceManager.GetString("productGetByIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getBySkuProducts.
        /// </summary>
        public static string productGetBySkuMethod {
            get {
                return ResourceManager.GetString("productGetBySkuMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getProducts.
        /// </summary>
        public static string productGetMethod {
            get {
                return ResourceManager.GetString("productGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saveProduct.
        /// </summary>
        public static string productSaveMethod {
            get {
                return ResourceManager.GetString("productSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product object.
        /// </summary>
        public static string responseBadRequestProduct {
            get {
                return ResourceManager.GetString("responseBadRequestProduct", resourceCulture);
            }
        }
    }
}
